### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Make the html & css file for your page.
- [x] Make the car image appear on the browser.
- [x] Remove unnecessary styling or tags.
