### ISSUE TITLE
Feature 2 : User can turn their car

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Make a data model for the directions (north, south, east, west)
- [x] Use the keydown event listener to make the car move
- [x] Remove any unnecessary comments or console.logs
